using System.Collections.Generic;

namespace RomajiTyping
{
    public partial class RomajiConverter
    {
         static IEnumerable<RomajiPair> GetSimplePairs()
        {
            return new[]
            {
                new RomajiPair("la", "ぁ"),
                new("xa", "ぁ"),
                new("a", "あ"),
                new("li", "ぃ"),
                new("lyi", "ぃ"),
                new("xi", "ぃ"),
                new("xyi", "ぃ"),
                new("i", "い"),
                new("yi", "い"),
                new("ye", "いぇ"),
                new("lu", "ぅ"),
                new("xu", "ぅ"),
                new("u", "う"),
                new("whu", "う"),
                new("wu", "う"),
                new("wha", "うぁ"),
                new("wi", "うぃ"),
                new("we", "うぇ"),
                new("whe", "うぇ"),
                new("who", "うぉ"),
                new("le", "ぇ"),
                new("lye", "ぇ"),
                new("xe", "ぇ"),
                new("xye", "ぇ"),
                new("e", "え"),
                new("lo", "ぉ"),
                new("xo", "ぉ"),
                new("o", "お"),
                new("ka", "か"),
                new("ca", "か"),
                new("ga", "が"),
                new("ki", "き"),
                new("kyi", "きぃ"),
                new("kye", "きぇ"),
                new("kya", "きゃ"),
                new("kyu", "きゅ"),
                new("kyo", "きょ"),
                new("gi", "ぎ"),
                new("gyi", "ぎぃ"),
                new("gye", "ぎぇ"),
                new("gya", "ぎゃ"),
                new("gyu", "ぎゅ"),
                new("gyo", "ぎょ"),
                new("ku", "く"),
                new("cu", "く"),
                new("qu", "く"),
                new("kwa", "くぁ"),
                new("qa", "くぁ"),
                new("qwa", "くぁ", ConversionMode.MS),
                new("kwa", "くぁ", ConversionMode.Google),
                new("qi", "くぃ"),
                new("qwi", "くぃ", ConversionMode.MS),
                new("qyi", "くぃ", ConversionMode.MS),
                new("kwi", "くぃ", ConversionMode.Google),
                new("qwu", "くぅ"),
                new("kwu", "くぅ", ConversionMode.Google),
                new("qe", "くぇ"),
                new("qwe", "くぇ", ConversionMode.MS),
                new("qye", "くぇ", ConversionMode.MS),
                new("kwe", "くぇ", ConversionMode.Google),
                new("qo", "くぉ"),
                new("qwo", "くぉ", ConversionMode.MS),
                new("kwo", "くぉ", ConversionMode.Google),
                new("qya", "くゃ", ConversionMode.MS),
                new("qyu", "くゅ", ConversionMode.MS),
                new("qyo", "くょ", ConversionMode.MS),
                new("gu", "ぐ"),
                new("gwa", "ぐぁ"),
                new("gwi", "ぐぃ"),
                new("gwu", "ぐぅ"),
                new("gwe", "ぐぇ"),
                new("gwo", "ぐぉ"),
                new("ke", "け"),
                new("ge", "げ"),
                new("ko", "こ"),
                new("co", "こ"),
                new("go", "ご"),
                new("sa", "さ"),
                new("za", "ざ"),
                new("shi", "し"),
                new("si", "し"),
                new("ci", "し"),
                new("syi", "しぃ"),
                new("sha", "しゃ"),
                new("sya", "しゃ"),
                new("shu", "しゅ"),
                new("syu", "しゅ"),
                new("she", "しぇ"),
                new("sye", "しぇ"),
                new("syo", "しょ"),
                new("sho", "しょ"),
                new("ji", "じ"),
                new("zi", "じ"),
                new("jyi", "じぃ"),
                new("zyi", "じぃ"),
                new("je", "じぇ"),
                new("jye", "じぇ"),
                new("zye", "じぇ"),
                new("ja", "じゃ"),
                new("jya", "じゃ"),
                new("zya", "じゃ"),
                new("ju", "じゅ"),
                new("jyu", "じゅ"),
                new("zyu", "じゅ"),
                new("jo", "じょ"),
                new("jyo", "じょ"),
                new("zyo", "じょ"),
                new("su", "す"),
                new("swa", "すぁ"),
                new("swi", "すぃ"),
                new("swu", "すぅ"),
                new("swe", "すぇ"),
                new("swo", "すぉ"),
                new("zu", "ず"),
                new("se", "せ"),
                new("ce", "せ"),
                new("ze", "ぜ"),
                new("so", "そ"),
                new("zo", "ぞ"),
                new("ta", "た"),
                new("da", "だ"),
                new("chi", "ち"),
                new("ti", "ち"),
                new("cyi", "ちぃ"),
                new("tyi", "ちぃ"),
                new("che", "ちぇ"),
                new("cye", "ちぇ"),
                new("tye", "ちぇ"),
                new("cha", "ちゃ"),
                new("tya", "ちゃ"),
                new("chu", "ちゅ"),
                new("cyu", "ちゅ"),
                new("tyu", "ちゅ"),
                new("cho", "ちょ"),
                new("cyo", "ちょ"),
                new("tyo", "ちょ"),
                new("di", "ぢ"),
                new("dyi", "ぢぃ"),
                new("dye", "ぢぇ"),
                new("dya", "ぢゃ"),
                new("dyu", "ぢゅ"),
                new("dyo", "ぢょ"),
                new("ltsu", "っ"),
                new("xtu", "っ"),
                new("tsu", "つ"),
                new("tu", "つ"),
                new("tsa", "つぁ"),
                new("tsi", "つぃ"),
                new("tse", "つぇ"),
                new("tso", "つぉ"),
                new("du", "づ"),
                new("te", "て"),
                new("thi", "てぃ"),
                new("the", "てぇ"),
                new("tha", "てゃ"),
                new("thu", "てゅ"),
                new("tho", "てょ"),
                new("de", "で"),
                new("dhi", "でぃ"),
                new("dhe", "でぇ"),
                new("dha", "でゃ"),
                new("dhu", "でゅ"),
                new("dho", "でょ"),
                new("to", "と"),
                new("twa", "とぁ"),
                new("twi", "とぃ"),
                new("twu", "とぅ"),
                new("t'u", "とぅ", ConversionMode.Google),
                new("twe", "とぇ"),
                new("two", "とぉ"),
                new("do", "ど"),
                new("dwa", "どぁ"),
                new("dwi", "どぃ"),
                new("dwu", "どぅ"),
                new("d'u", "どぅ", ConversionMode.Google),
                new("dwe", "どぇ"),
                new("dwo", "どぉ"),
                new("na", "な"),
                new("ni", "に"),
                new("nyi", "にぃ"),
                new("nye", "にぇ"),
                new("nya", "にゃ"),
                new("nyu", "にゅ"),
                new("nyo", "にょ"),
                new("nu", "ぬ"),
                new("ne", "ね"),
                new("no", "の"),
                new("ha", "は"),
                new("ba", "ば"),
                new("pa", "ぱ"),
                new("hi", "ひ"),
                new("hyi", "ひぃ"),
                new("hye", "ひぇ"),
                new("hya", "ひゃ"),
                new("hyu", "ひゅ"),
                new("hyo", "ひょ"),
                new("bi", "び"),
                new("byi", "びぃ"),
                new("bye", "びぇ"),
                new("bya", "びゃ"),
                new("byu", "びゅ"),
                new("byo", "びょ"),
                new("pi", "ぴ"),
                new("pyi", "ぴぃ"),
                new("pye", "ぴぇ"),
                new("pya", "ぴゃ"),
                new("pyu", "ぴゅ"),
                new("pyo", "ぴょ"),
                new("fu", "ふ"),
                new("hu", "ふ"),
                new("fa", "ふぁ"),
                new("fwa", "ふぁ"),
                new("fi", "ふぃ"),
                new("fwi", "ふぃ"),
                new("fyi", "ふぃ"),
                new("fwu", "ふぅ"),
                new("fe", "ふぇ"),
                new("fo", "ふぉ"),
                new("fwo", "ふぉ"),
                new("fya", "ふゃ"),
                new("fyu", "ふゅ"),
                new("fyo", "ふょ"),
                new("bu", "ぶ"),
                new("pu", "ぷ"),
                new("he", "へ"),
                new("be", "べ"),
                new("pe", "ぺ"),
                new("ho", "ほ"),
                new("bo", "ぼ"),
                new("po", "ぽ"),
                new("ma", "ま"),
                new("mi", "み"),
                new("myi", "みぃ"),
                new("mye", "みぇ"),
                new("mya", "みゃ"),
                new("myu", "みゅ"),
                new("myo", "みょ"),
                new("mu", "む"),
                new("me", "め"),
                new("mo", "も"),
                new("lya", "ゃ"),
                new("xya", "ゃ"),
                new("ya", "や"),
                new("lyu", "ゅ"),
                new("xyu", "ゅ"),
                new("yu", "ゆ"),
                new("lyo", "ょ"),
                new("xyo", "ょ"),
                new("yo", "よ"),
                new("ra", "ら"),
                new("ri", "り"),
                new("ryi", "りぃ"),
                new("rye", "りぇ"),
                new("rya", "りゃ"),
                new("ryu", "りゅ"),
                new("ryo", "りょ"),
                new("ru", "る"),
                new("re", "れ"),
                new("ro", "ろ"),
                new("lwa", "ゎ"),
                new("xwa", "ゎ"),
                new("wa", "わ"),
                new("wyi", "ゐ"),
                new("wye", "ゑ"),
                new("wo", "を"),
                new("nn", "ん"),
                new("xn", "ん"),
                new("n'", "ん"),
                new("vu", "ヴ"),
                new("va", "ヴぁ"),
                new("vi", "ヴぃ"),
                new("vyi", "ヴぃ"),
                new("ve", "ヴぇ"),
                new("vye", "ヴぇ"),
                new("vo", "ヴぉ"),
                new("vya", "ヴゃ"),
                new("vyu", "ヴゅ"),
                new("vyo", "ヴょ"),
                new("lka", "ヵ"),
                new("xka", "ヵ"),
                new("lke", "ヶ"),
                new("xke", "ヶ"),
            };
        }


        public static IEnumerable<RomajiPair> DefaultPairs()
        {
            yield return new("n", "ん");
            foreach (var pair in GetSimplePairs())
            {
                yield return pair;
                var romaji = pair.Romaji;
                var hiragana = pair.Kana;
                yield return new(romaji, hiragana);

                if (romaji[0] is not ('a' or 'i' or 'u' or 'e' or 'o'　or 'n'))
                {
                    yield return pair with { Romaji = romaji[0] + romaji, Kana = "っ" + hiragana };
                }
            }
        }
    }
}